import {siteUrl} from '@/lib/site-url';
export const knowledge = [
{keywords:['booking','patient','journey','results','impact','metrics','research','testing','focus','usability'],text:'For Vosita’s booking redesign, Omar analyzed the journey across search, results, signup and confirmation. He simplified search, made mobile results compact, preserved context with a signup modal, and redesigned booking as a single-column form. The case study reports average journey time dropping from 11 to 4.2 minutes and 100% completion in follow-up testing. The published source does not provide participant counts; these are study results, not a production-wide guarantee.',label:'Booking case study',url:siteUrl('/work/booking')},
{keywords:['system','systems','component','components','tokens','figma','bootstrap','developer','handoff','collaboration','scalable','library'],text:'Omar consolidated Vosita’s Adobe XD and Figma work into Figma, standardized colors and typography, introduced a 4-point spacing system and design tokens, and built reusable components and templates. He worked with the front-end lead, documented designs in an Azure wiki, and introduced Ready for Dev handoff. His resume describes a Bootstrap-aligned UI library. The sources report qualitative efficiency improvements without a numerical measurement.',label:'Design system case study',url:siteUrl('/work/design-system')},
{keywords:['profile','profiles','provider','hierarchy','architecture','navigation'],text:'Omar redesigned Vosita’s provider profiles around a clearer information hierarchy. A persistent sidebar keeps booking accessible, reviews expand in place, and secondary mobile content is collapsible. The case study reports qualitative improvements in engagement and progression to booking; it does not supply numerical conversion results.',label:'Provider profile case study',url:siteUrl('/work/provider-profile')},
{keywords:['experience','career','work','worked','role','roles','resume','background','vosita','microwize','years'],text:'Omar’s resume lists these roles: UI/UX Designer at Vosita (2022–present), Senior Graphic Designer at Microwize (2023–present), Graphic Designer & Branding Coordinator at Microwize (2022–2023), and freelance designer (2017–2022). His UX work covers research, web and mobile redesign, prototyping, design systems and developer handoff. These dates reflect the supplied resume.',label:'Omar’s resume'},
{keywords:['education','degree','waterloo','university','study','studied','master','certificate','google','accounting'],text:'The supplied resume lists a Master of Digital Experience Innovation at the University of Waterloo, August 2026–April 2027 (expected), a Bachelor of Accounting from Ain Shams University (2017–2021), and a Google UX Design Certificate (2025). The master’s degree is listed as expected, not completed.',label:'Education in resume'},
{keywords:['tools','skills','adobe','software','html','css','language','languages','arabic','english'],text:'Omar’s listed tools include Figma and Adobe Photoshop, Illustrator, Premiere, XD, InDesign and After Effects. His research skills include journey mapping, focus groups, usability testing and data analysis. He lists basic HTML/CSS knowledge, native Arabic and bilingual English proficiency.',label:'Skills in resume'},
{keywords:['branding','brand','graphic','motion','animation','illustration','logo','ads','creative'],text:'Alongside UX, Omar modernized Microwize’s legacy visual identity, created brand guidelines and characters, and designed and animated Vosita marketing work. For the campaign videos, he also wrote scripts. His Brand & Motion page includes JKR Windows advertising and selected graphic design work.',label:'Brand & visual work',url:siteUrl('/visual-work')},
{keywords:['contact','email','hire','hiring','availability','available','salary','relocate','relocation','rate','rates'],text:'You can contact Omar at contact@omarmansour.online about product and UX opportunities. The provided materials do not confirm his current availability, salary expectations, rates or relocation preferences, so please ask him directly.',label:'Contact Omar',url:'mailto:contact@omarmansour.online'},
{keywords:['signup','login','authentication','registration'],text:'Omar simplified Vosita’s split-screen signup/login layout, clarified the alternate login and signup links, reduced redundant fields, added progress-loss confirmation, embedded verification and improved the post-signup handoff. The case study explicitly says formal metrics were not tracked.',label:'Signup and login case study',url:siteUrl('/work/booking')}
];
export function answer(question:string){const words:string[]=question.toLowerCase().match(/[a-zà-ž]+/g)||[];if(words.some(w=>['ignore','instruction','systemprompt','secret'].includes(w)))return {text:'I can help with Omar’s published work and resume. Try asking about his booking redesign, design system or experience.'};const ranked=knowledge.map(k=>({k,score:k.keywords.reduce((n,w)=>n+(words.includes(w)?1:0),0)})).sort((a,b)=>b.score-a.score);if(!ranked[0].score)return {text:'I don’t have a sourced answer to that question. You can ask about Omar’s projects, experience, education or skills—or contact him at contact@omarmansour.online.',label:'Contact Omar',url:'mailto:contact@omarmansour.online'};return ranked[0].k;}


